#!/bin/dash

# COMP2041 assignment 1 (system version control) 
# svc-commit
# 
# Written by Saba Kiani (z5592529)
# saba.kiani@student.unsw.edu.au
# On 05/07/2026
#
# Creates a new "commit" file and copies the 
# files from index/home directory into it, with a message

# Function that conducts the commit process.
# Commits a snapshot of the files staged in the index
# directory in .svc with a commit message.
operate_commit() {
    commitMessage="$1"

    # Confirm .svc directory exists
    if [ ! -d ".svc" ]; then
        echo "svc-commit: error: svc repository directory .svc not found" >&2
        exit 1
    fi

    # Acquire latest commit number from tracking file
    latestCommit=$(cat ".svc/svc-trackCommits")
    indexFileCount=$(find ".svc/index" -type f | wc -l)
    
    # Check if no changes in index since last commit
    # find differences in the directories, excluding message file
    if [ "$latestCommit" -ge 0 ] && diff -x "message" -q -r ".svc/index" ".svc/commit_$latestCommit"  >/dev/null 2>&1; then
        echo "nothing to commit"
        exit 1
    fi
    
    if [ "$latestCommit" -eq -1 ] && [ "$indexFileCount" -eq 0 ]; then 
        echo "nothing to commit"
        exit 1
    fi
    
    # Increment and overwrite new latest commit number
    latestCommit=$((latestCommit + 1))
    echo "$latestCommit" > ".svc/svc-trackCommits"

    # Construct the directory for this commit
    mkdir -p ".svc/commit_$latestCommit" 
    echo "Committed as commit $latestCommit"

    # Copy valid files from index to new commit folder
        for currFile in .svc/index/*; do
            # If the current file doesnt exist, then continue
            if [ ! -e "$currFile" ]; then
                continue
            else 
                cp "$currFile" ".svc/commit_$latestCommit/"
            fi
        done
    
    # Add a message file to the commit directory
    echo "$commitMessage" > ".svc/commit_$latestCommit/message"
}

# Function that updates all files in the index
# with the ones in the original directory,
# If requested by the user with "-a".
update_index () {
    for currentFile in .svc/index/*; do 
        # Only update if this file is actually a file
        if [ -f "$currentFile" ]; then
            newFile=$(basename "$currentFile") 

            # If file exists in current directory, update
            if [ -f "$newFile" ]; then 
                cp "$newFile" "$currentFile"
            else 
                # If the file is absent locally, 
                # delete the one in index
                rm "$currentFile"
            fi
        fi
    done 
}

# Confirm command line arguments' number and syntax
if [ $# -eq 3 ] && [ "$1" = "-a" ] && [ "$2" = "-m" ]; then 
    update_index
    message="$3"
    operate_commit "$message"
elif [ $# -eq 2 ] && [ "$1" = "-m" ]; then
    message="$2"
    operate_commit "$message"
else 
    echo "usage: svc-commit [-a] -m commit-message"
    exit 1
fi